apiVersion: v1
kind: Pod
metadata:
  name: obsv-control-agent
  namespace: obsv-control-agent
spec:
  serviceAccountName: obsv-control-agent
  containers:
    - name: operator
      image: hremon331046/control-agent:latest
      imagePullPolicy: IfNotPresent
  restartPolicy: Never