apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "control-agent.fullname" . }}
  labels:
    {{- include "control-agent.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - nodes
      - configmaps
    verbs:
      - watch
      - get
      - list
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "control-agent.fullname" . }}
  labels:
    {{- include "control-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "control-agent.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "control-agent.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "control-agent.serviceAccountName" . }}
  labels:
    {{- include "control-agent.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
